<?php

function getLanguageStrings($lang = 'en') {
    $languages = [
        'en' => [
            // ============ NAVIGATION ============
            'dashboard' => 'Dashboard',
            'my_tasks' => 'My Tasks',
            'attendance' => 'Attendance',
            'leave' => 'Apply Leave',
            'my_leave' => 'My Leave',
            'inventory' => 'Inventory',
            'maintenance' => 'Maintenance',
            'my_performance' => 'My Performance',
            'profile' => 'Profile',
            'logout' => 'Logout',
            
            // Admin Navigation
            'user_management' => 'User Management',
            'task_management' => 'Task Management',
            'leave_management' => 'Leave Management',
            'attendance_tracking' => 'Attendance Tracking',
            'employee_performance' => 'Employee Performance',
            'bin_monitoring' => 'Bin Monitoring',
            'waste_analytics' => 'Waste Analytics',
            'supply_requests' => 'Supply Requests',
            'maintenance_reports' => 'Maintenance Reports',
            
            // ============ DASHBOARD ============
    'welcome_back' => 'Welcome back',
    'pending_tasks' => 'Pending Tasks',
    'completed_today' => 'Completed Today',
    'completed_this_month' => 'Completed This Month',
    'performance' => 'Performance',
    'todays_tasks' => "Today's Tasks",
    'no_tasks_today' => 'No tasks for Now',
    'enjoy_your_day' => '',
    'start_task' => 'Start Task',
    'complete_task' => 'Complete',
    'urgent_tasks' => 'Urgent Tasks',
    'view_all' => 'View All',
    'quick_stats' => 'Quick Stats',
    'present_days_month' => 'Early Arrivals',
    'late_arrivals' => 'Late Arrivals',
    'completion_rate' => 'Completion Rate',
    'recently_completed' => 'Recently Completed',
    'total_tasks' => 'Total Tasks',
            
            // ============ TASKS ============
            'tasks' => 'Tasks',
            'task_title' => 'Task Title',
            'task_description' => 'Task Description',
            'status' => 'Status',
            'priority' => 'Priority',
            'due_date' => 'Due Date',
            'assigned_by' => 'Assigned By',
            'assigned_to' => 'Assigned To',
            'actions' => 'Actions',
            'mark_complete' => 'Mark Complete',
            'view_details' => 'View Details',
            'add_task' => 'Add Task',
            'edit_task' => 'Edit Task',
            'delete_task' => 'Delete Task',
            'task_details' => 'Task Details',
            'low' => 'Low',
            'medium' => 'Medium',
            'high' => 'High',
            'pending' => 'Pending',
            'completed' => 'Completed',
            'overdue' => 'Overdue',
            'my_tasks' => 'My Tasks',
'todays_tasks' => "Today's Tasks",
'active_tasks' => 'Active Tasks',
'tasks_history' => 'Tasks History',
'task_list' => 'Task List',
'tasks' => 'tasks',
'all_clear' => 'All Clear',
'you_have_no' => 'You have no',
'no_active_tasks' => 'You have no active tasks',
'no_today_tasks' => 'You have no tasks scheduled for today',
'no_tasks_found' => 'No tasks found',
'auto' => 'AUTO',
'type' => 'Type',
'area' => 'Area',
'bin' => 'Bin',
'full' => 'full',
'due' => 'Due',
'overdue' => 'Overdue',
'at' => 'at',
'view_on_map' => 'View on Map',
'complete_task' => 'Complete Task',
'add_completion_notes' => 'Add any notes about this task (optional)',
'any_issues_placeholder' => 'Any issues or notes about completion?',

// ============ TASK ACTIONS ============
'task_created_success' => 'Task created successfully!',
'task_not_found' => 'Task not found',
'cannot_edit_completed_cancelled' => 'Cannot edit completed or cancelled tasks',
'task_updated_success' => 'Task updated successfully!',
'auto_generated_collection_report_admin' => 'Auto-generated collection report (admin completed)',
'cannot_cancel_completed' => 'Cannot cancel completed tasks',
'task_cancelled_success' => 'Task cancelled successfully',
'only_pending_can_start' => 'Only pending tasks can be started',
'task_started_success' => 'Task started successfully',
'task_not_found_not_assigned' => 'Task not found or not assigned to you',
'task_already_started' => 'This task has already been started',
'task_started_good_luck' => 'Task started! Good luck!',
'task_already_completed' => 'This task is already completed',
'cannot_complete_cancelled' => 'Cannot complete a cancelled task',
'auto_generated_collection_report' => 'Auto-generated collection report',
'task_completed_great_job' => 'Task completed successfully! Great job!',
'task_deleted_success' => 'Task deleted successfully',
'invalid_action_insufficient_permissions' => 'Invalid action or insufficient permissions',

// ============ ATTENDANCE DASHBOARD ============
'mark_your_attendance' => 'Mark Your Attendance',
'go_to_check_in_out' => 'Go to Check In/Out',
'current_time' => 'Current Time',
'present_days' => 'Early Arrivals',
'absent_days' => 'Absent Days',
'total_hours' => 'Total Hours',
'attendance_records' => 'Attendance Records',
'no_records_found' => 'No Records Found',
'no_attendance_records_month' => 'No attendance records for this month',
'check_in' => 'Check In',
'check_out' => 'Check Out',
'hours' => 'Hours',
'todays_status' => "Today's Status",
'not_checked_in' => 'Not Checked In',
'havent_checked_in_today' => "You haven't checked in today yet.",
            
            // ============ CHECK IN/OUT PAGE ============
'check_in_out' => 'Check In/Out',
'welcome' => 'Welcome',
'please_select_employee' => "Please select an employee from the 'Check In/Out' dropdown in the Attendance page",
'employee_not_found' => 'Employee not found',
'detecting_location' => 'Detecting your location...',
'location_detected' => 'Location detected successfully',
'location_error' => 'Unable to detect location. Please enable GPS.',
'geolocation_not_supported' => 'Geolocation is not supported by your browser',
'location_not_detected_alert' => 'Location not detected!',
'enable_gps_refresh' => 'Please enable GPS and refresh the page.',
'todays_attendance_record' => "Today's Attendance Record",
'check_in_time' => 'Check In Time',
'check_out_time' => 'Check Out Time',
'hours' => 'hrs',
'check_in_now' => 'Check In Now',
'check_out_now' => 'Check Out',
'or' => 'Or',
'back_to' => 'Back to',
'my_attendance' => 'My Attendance',

// Status Messages
'status_on_time' => 'On Time',
'status_late_arrival' => 'Late Arrival',
'status_very_late' => 'Very Late',

// Late Reason
'reason_late_arrival' => 'Reason for Late Arrival',
'required' => 'Required',
'optional' => 'Optional',
'explain_late_reason' => 'Please explain why you\'re checking in late...',
'checkin_after_noon_warning' => 'Check-ins after 12 PM require manager approval. Please provide a valid reason.',
'late_reason_help' => 'This will help your manager understand the situation.',

// ============ PERFORMANCE PAGE ============
'my_performance_report' => 'My Performance Report',
'back_to_dashboard' => 'Back to Dashboard',
'performance_report_for' => 'Your performance report for',
'select_time_period' => 'Select Time Period',
'current_month' => 'Current Month',
'current_month_display' => date('F Y'),
'overall_performance_score' => 'Overall Performance Score',
'task_completion_rate' => 'Task Completion Rate',
'on_time_completion_rate' => 'On-Time Completion Rate',
'attendance_rate' => 'Attendance Rate',
'efficiency_score' => 'Efficiency Score',
'weight_30_percent' => 'Weight: 30% of overall score',
'weight_25_percent' => 'Weight: 25% of overall score',
'weight_15_percent' => 'Weight: 15% of overall score',
'tasks_assigned' => 'Tasks Assigned',
'tasks_completed' => 'Tasks Completed',
'bins_collected' => 'Bins Collected',
'weight_collected' => 'Weight Collected',
'attendance_days' => 'Attendance Days',
'avg_response_time' => 'Avg Response Time',
'on_time_tasks' => 'On-Time Tasks',
'performance_trend_6_months' => 'Performance Trend (Last 6 Months)',
'overall_score' => 'Overall Score',
'completion_rate_chart' => 'Completion Rate',
'on_time_rate_chart' => 'On-Time Rate',
'attendance_rate_chart' => 'Attendance Rate',
'last_7_days' => '7 Days Ago',
'last_30_days' => '30 Days Ago',
'all_time' => 'All Time',

// Performance Grades
'grade_excellent' => 'Excellent',
'grade_good' => 'Good',
'grade_average' => 'Average',
'grade_needs_improvement' => 'Needs Improvement',
'grade_poor' => 'Poor',

            // ============ LEAVE ============
            'apply_leave' => 'Request Leave',
            'leave_requests' => 'Leave Requests',
            'leave_type' => 'Leave Type',
            'start_date' => 'Start Date',
            'end_date' => 'End Date',
            'total_days' => 'Total Days',
            'reason' => 'Reason',
            'emergency_contact' => 'Emergency Contact',
            'emergency_phone' => 'Emergency Phone',
            'annual_leave' => 'Annual Leave',
            'sick_leave' => 'Sick Leave',
            'emergency_leave' => 'Emergency Leave',
            'unpaid_leave' => 'Unpaid Leave',
            'maternity_leave' => 'Maternity Leave',
            'paternity_leave' => 'Paternity Leave',
            'approved' => 'Approved',
            'rejected' => 'Rejected',
            'cancelled' => 'Cancelled',
            'used_days' => 'Used Days',
            'remaining_days' => 'Remaining Days',
            'approve' => 'Approve',
            'reject' => 'Reject',
            'submit_leave_for_approval' => 'Submit a leave request for approval',
            'leave_request_form' => 'Leave Request Form',
            'select_leave_type' => 'Select leave type',
            'total_days_requested' => 'Total Days Requested',
            'leave_reason_placeholder' => 'Please provide details for your leave request...',
            'contact_person_during_leave' => 'Contact person during leave',
            'leave_balance' => 'Leave Balance',
            'no_leave_balance_data' => 'No leave balance data available',
            'used' => 'Used',
            'days' => 'days',
            'request_leave' => 'Request Leave',
            'all' => 'All',
            'no_leave_requests_found' => 'No leave requests found',
            'havent_requested_leave' => "You haven't requested any leave yet",
            'request_leave_now' => 'Request Leave Now',
            'day' => 'day',
            'applied' => 'Applied',
            'reviewed' => 'Reviewed',
            'cancel_leave_confirm' => 'Cancel this leave request?',
            'cancel_request' => 'Cancel Request',
            'only_employees_can_request_leave' => 'Only employees can request leave',
'end_date_after_start_date' => 'End date must be after start date',
'invalid_leave_type' => 'Invalid leave type',
'insufficient_leave_balance' => 'Insufficient leave balance',
'you_have' => 'You have',
'days_remaining' => 'days remaining',
'overlapping_leave_request' => 'You already have a leave request for overlapping dates',
'leave_request_submitted' => 'Leave request submitted successfully! Waiting for approval.',
'invalid_leave_request_id' => 'Invalid leave request ID',
'leave_request_not_found' => 'Leave request not found',
'cancel_own_leave_only' => 'You can only cancel your own leave requests',
'only_pending_can_cancel' => 'Only pending leave requests can be cancelled',
'leave_request_cancelled' => 'Leave request cancelled successfully',
'only_admins_can_approve' => 'Only admins can approve leave requests',
'already_processed' => 'This leave request has already been processed',
'leave_request_approved' => 'Leave request approved successfully',
'only_admins_can_reject' => 'Only admins can reject leave requests',
'provide_rejection_reason' => 'Please provide a reason for rejection',
'leave_request_rejected' => 'Leave request rejected',
            

            // ============ INVENTORY ============
            'inventory_management' => 'Inventory Management',
            'item_name' => 'Item Name',
            'total_items' => 'Total Items',
            'search_items' => 'Search items',
            'all_categories' => 'All Categories',
            'min_quantity' => 'Min. Quantity',
            'category' => 'Category',
            'quantity' => 'Quantity',
            'current_quantity' => 'Current Quantity',
            'minimum_quantity' => 'Minimum Quantity',
            'unit' => 'Unit',
            'location' => 'Location',
            'storage_location' => 'Storage Location',
            'take' => 'Take',
            'request_restock' => 'Request Restock',
            'available' => 'Available',
            'low_stock' => 'Low Stock',
            'out_of_stock' => 'Out of Stock',
            'in_stock' => 'In Stock',
            'my_recent_transactions' => 'My Recent Transactions',
            'view_my_requests' => 'View My Requests',
            'quantity_requested' => 'Quantity Requested',
            'urgency' => 'Urgency',
            'safety_gear' => 'Safety gear',
            'invalid_action' => 'Invalid action',
'invalid_item_or_quantity' => 'Invalid item or quantity',
'insufficient_stock' => 'Insufficient stock',
'only' => 'Only',
'of' => 'of',
'self_service_take' => 'Self-service take',
'successfully_taken' => 'Successfully taken',
'remaining' => 'Remaining',
'failed_to_record_transaction' => 'Failed to record transaction',
'no_items_found' => 'No Item Found',        

// ============ SUPPLY REQUEST ACTIONS ============
'select_item_valid_quantity' => 'Please select an item and enter a valid quantity',
'invalid_urgency_level' => 'Invalid urgency level',
'restock_request_submitted' => 'Restock request submitted successfully',
'your_request_for' => 'Your request for',
'awaiting_admin_approval' => 'is awaiting admin approval',
'quantity_to_restock' => 'Quantity To Restock',
'enter_quantity_restock' => '',
'why_need_this' => '',

            // ============ SUPPLY REQUESTS PAGE ============
'supply_requests' => 'Supply Requests',
'back_to_inventory' => 'Back to Inventory',
'new_request' => 'New Request',
'my_requests' => 'My Requests',
'submit_request' => 'Submit Request',
'reason_optional_recommended' => 'Reason',
'submit_supply_request' => 'Submit Supply Request',
'select_item' => 'Select Item',
'choose_item' => 'Choose an item',
'available_stock' => 'Available Stock',
'quantity_requested' => 'Quantity Requested',
'enter_quantity' => 'Enter quantity',
'urgency_low_desc' => 'Low',
'urgency_medium_desc' => 'Medium',
'urgency_high_desc' => 'High - Urgent/Emergency',
'reason_placeholder' => 'Why do you need this item? Providing details helps admin process your request faster.',
'reason_hint' => 'Example: "Need extra trash bags for community cleanup event" or "Current broom is damaged"',
'total_requests' => 'Total Requests',
'fulfilled' => 'Fulfilled',
'all_requests' => 'All Requests',
'no_supply_requests_yet' => 'No Supply Requests Yet',
'havent_submitted_requests' => "You haven't submitted any supply requests",
'create_first_request' => 'Create First Request',
'priority' => 'Priority',
'current_stock' => 'Current Stock',
'requested_date' => 'Requested Date',
'processed_date' => 'Processed Date',
'your_reason' => 'Your Reason',
'admin_response' => 'Admin Response',
'reviewed_by' => 'Reviewed by',
'awaiting_admin_review' => 'Awaiting admin review...',
'item_restocked' => 'Item Restocked',
'awaiting_fulfillment' => 'Awaiting Fulfillment',
'request_rejected' => 'Request Rejected',

            // ============ MAINTENANCE ============
            'report_issue' => 'Report Issue',
            'my_reports' => 'My Reports',
            'issue_title' => 'Issue Title',
            'issue_description' => 'Issue Description',
            'issue_category' => 'Issue Category',
            'description' => 'Description',
            'photo' => 'Photo',
            'photo_evidence' => 'Photo Evidence',
            'reported_by' => 'Reported By',
            'reported_at' => 'Reported At',
            'resolved' => 'Resolved',
            'resolved_at' => 'Resolved At',
            'admin_notes' => 'Admin Notes',
            'bin_issue' => 'Bin Issue',
            'equipment_issue' => 'Equipment Issue',
            'facility_issue' => 'Facility Issue',
            'safety_hazard' => 'Safety Hazard',
            'other' => 'Other',
            'my_issue_reports' => 'My Issue Reports',
'new_report' => 'New Report',
'total_reports' => 'Total Reports',
'in_progress' => 'In Progress',
'all_status' => 'All Status',
'no_reports_yet' => 'No Reports Yet',
'havent_submitted_reports' => "You haven't submitted any maintenance reports",
'create_first_report' => 'Create First Report',
'resolved_date' => 'Resolved Date',
'issue_photo' => 'Issue photo',
'cancel_report_confirm' => 'Cancel this report? This action cannot be undone.',
'cancel_report' => 'Cancel Report',
'issue_resolved' => 'Issue Resolved',
'being_worked_on' => 'Being Worked On',
            
// ============ REPORT ISSUE PAGE ============
'submit_maintenance_report' => 'Submit Maintenance Report',
'issue_title' => 'Issue Title',
'issue_title_placeholder' => 'e.g., Broken bin lid at Area A1',
'select_category' => 'Select category',
'issue_description' => 'Issue Description',
'issue_description_placeholder' => 'Describe the issue in detail...',
'photo_evidence_optional' => 'Photo Evidence',
'max_5mb_jpg_png' => 'Max 5MB, JPG/PNG only',
'photo_preview' => 'Photo preview',
'location_placeholder' => 'e.g., Area A1, Building 3, Floor 2',
'submit_report' => 'Submit Report',
'view_my_reports' => 'View My Reports',

// ============ REPORT ACTIONS ============
'invalid_issue_category' => 'Invalid issue category',
'invalid_priority_level' => 'Invalid priority level',
'report_submitted_success' => 'Maintenance report submitted successfully! Admin will review your report soon.',
'failed_upload_photo' => 'Failed to upload photo. Please try again.',
'invalid_report_id' => 'Invalid report ID',
'report_not_found_no_permission' => "Report not found or you don't have permission to cancel it",
'only_pending_reports_cancel' => 'Only pending reports can be cancelled. This report is already being processed.',
'report_cancelled_success' => 'Report cancelled successfully.',

// Priority Descriptions
'priority_low_desc' => 'Low priority - will be addressed when possible',
'priority_medium_desc' => 'Normal priority - will be addressed soon',
'priority_high_desc' => 'High priority - urgent attention needed!',

// Validation Messages
'file_size_error' => 'File size must be less than 5MB!',
'file_type_error' => 'Only JPG and PNG images are allowed!',
'fill_all_required_fields' => 'Please fill in all required fields!',
'title_too_short' => 'Issue title must be at least 5 characters long!',
'description_too_short' => 'Please provide a more detailed description (at least 10 characters)!',
'confirm_submit_report' => 'Submit this maintenance report?',

            // ============ PROFILE ============
            'my_profile' => 'My Profile',
            'personal_information' => 'Personal Information',
            'account_settings' => 'Account Settings',
            'language_settings' => 'Language Settings',
            'full_name' => 'Full Name',
            'email' => 'Email',
            'phone' => 'Phone Number',
            'address' => 'Address',
            'date_of_birth' => 'Date of Birth',
            'hire_date' => 'Hire Date',
            'position' => 'Position',
            'department' => 'Department',
            'change_password' => 'Change Password',
            'current_password' => 'Current Password',
            'new_password' => 'New Password',
            'confirm_password' => 'Confirm Password',
            'update_profile' => 'Update Profile',
            'choose_language' => 'Choose Language',
            'select_language' => 'Select your preferred language',
            'english' => 'English',
            'malay' => 'Bahasa Malaysia',
            
            // ============ COMMON BUTTONS ============
            'submit' => 'Submit',
            'cancel' => 'Cancel',
            'save' => 'Save',
            'delete' => 'Delete',
            'edit' => 'Edit',
            'back' => 'Back',
            'close' => 'Close',
            'confirm' => 'Confirm',
            'add' => 'Add',
            'update' => 'Update',
            'create' => 'Create',
            'search' => 'Search',
            'filter' => 'Filter',
            'clear' => 'Clear',
            'export' => 'Export',
            'import' => 'Import',
            'download' => 'Download',
            'upload' => 'Upload',
            'print' => 'Print',
            'refresh' => 'Refresh',
            
            // ============ MESSAGES ============
            'loading' => 'Loading...',
            'no_data' => 'No data available',
            'success' => 'Success',
            'error' => 'Error',
            'warning' => 'Warning',
            'info' => 'Information',
            'confirm_delete' => 'Are you sure you want to delete this?',
            'confirm_action' => 'Are you sure you want to proceed?',
            'saved_successfully' => 'Saved successfully',
            'updated_successfully' => 'Updated successfully',
            'deleted_successfully' => 'Deleted successfully',
            'operation_failed' => 'Operation failed',
            'please_fill_required_fields' => 'Please fill in all required fields',
            'invalid_input' => 'Invalid input',
            'unauthorized_access' => 'Unauthorized access',
            'language_updated' => 'Language updated successfully',
            
            // ============ TIME & DATE ============
            'today' => 'Today',
            'yesterday' => 'Yesterday',
            'this_week' => 'This Week',
            'this_month' => 'This Month',
            'last_updated' => 'Last Updated',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'morning' => 'Morning',
            'afternoon' => 'Afternoon',
            'evening' => 'Evening',
            
            // ============ STATISTICS ============
            'total' => 'Total',
            'statistics' => 'Statistics',
            'overview' => 'Overview',
            'summary' => 'Summary',
            'details' => 'Details',
            'reports' => 'Reports',
            'analytics' => 'Analytics',

            // Profile Page
    'my_profile' => 'My Profile',
    'edit_profile' => 'Edit Profile Information',
    'waste_collection_employee' => 'Waste Collection Employee',
    'change_photo' => 'Change Photo',
    'not_set' => 'Not set',
    'not_assigned' => 'Not assigned',
    'joined' => 'Joined',
    'last_login' => 'Last Login',
    'cannot_be_changed' => 'cannot be changed',
    'area' => 'Area',
    'note' => 'Note',
    'admin_only_fields' => 'Username, assigned area, and account status can only be changed by administrators.',
    'enter_current_password' => 'Enter your current password',
    'enter_new_password' => 'Enter new password',
    'reenter_password' => 'Re-enter new password',
    'minimum_6_characters' => 'minimum 6 characters',
    'password_requirements' => 'Password Requirements',
    'password_requirement_text' => 'At least 6 characters long. Use a strong password to protect your account.',
    'invalid_file_type' => 'Invalid file type. Only JPG, JPEG, PNG, and GIF are allowed.',
    'file_too_large' => 'File size must be less than 5MB.',
    'profile_picture_updated' => 'Profile picture updated successfully!',
    'upload_failed' => 'Failed to upload profile picture.',
    'please_select_file' => 'Please select a valid image file.',
    'email_already_used' => 'Email is already in use by another account!',
    'profile_updated' => 'Profile updated successfully!',
    'all_fields_required' => 'All password fields are required!',
    'passwords_not_match' => 'New passwords do not match!',
    'password_min_length' => 'New password must be at least 6 characters!',
    'current_password_incorrect' => 'Current password is incorrect!',
    'password_changed' => 'Password changed successfully!',
        ],
        
        'ms' => [ // Bahasa Malaysia
            // ============ NAVIGASI ============
    'welcome_back' => 'Selamat kembali',
    'pending_tasks' => 'Tugas Belum Selesai',
    'completed_today' => 'Tugas Selesai Hari Ini',
    'completed_this_month' => 'Tugas Selesai Bulan Ini',
    'performance' => 'Prestasi',
    'todays_tasks' => 'Tugasan Hari Ini',
    'no_tasks_today' => 'Belum ada tugasan untuk hari ini',
    'enjoy_your_day' => '',
    'start_task' => 'Mula Tugasan',
    'complete_task' => 'Selesaikan',
    'urgent_tasks' => 'Tugasan Segera',
    'view_all' => 'Lihat Semua',
    'quick_stats' => 'Statistik Ringkas',
    'present_days_month' => 'Kehadiran Awal',
    'late_arrivals' => 'Kelewatan Ketibaan',
    'completion_rate' => 'Kadar Penyiapan',
    'recently_completed' => 'Tugasan Baru Selesai',
            
            // ============ NAVIGATION ============
            'dashboard' => 'Papan pemuka',
            'attendance' => 'Kehadiran',
            'maintenance' => 'Laporan Penyelenggaraan',
            'my_performance' => 'Prestasi Saya',
            'profile' => 'Profil',
            'logout' => 'Logout',

            // Navigasi Admin
            'user_management' => 'Pengurusan Pengguna',
            'task_management' => 'Pengurusan Tugasan',
            'leave_management' => 'Pengurusan Cuti',
            'attendance_tracking' => 'Penjejakan Kehadiran',
            'employee_performance' => 'Prestasi Pekerja',
            'bin_monitoring' => 'Pemantauan Tong',
            'waste_analytics' => 'Analitik Sisa',
            'supply_requests' => 'Permintaan Bekalan',
            'maintenance_reports' => 'Laporan Penyelenggaraan',
            
            // ============ PAPAN PEMUKA ============
            'welcome' => 'Selamat Datang',
            'welcome_back' => 'Selamat kembali',
            'total_tasks' => 'Jumlah Tugasan',
            'pending_tasks' => 'Tugas Belum Selesai',
            'in_progress' => 'Dalam Proses',
            'completed_tasks' => 'Selesai',
            'overdue_tasks' => 'Lewat Tarikh',
            'work_hours' => 'Jam Kerja Minggu Ini',
            'leave_balance' => 'Baki Cuti',
            'upcoming_tasks' => 'Tugasan Akan Datang',
            'recent_activities' => 'Aktiviti Terkini',
            
            // ============ TUGASAN ============
            'tasks' => 'Tugasan',
            'task_title' => 'Tajuk Tugasan',
            'task_description' => 'Keterangan Tugasan',
            'status' => 'Status',
            'priority' => 'Keutamaan',
            'due_date' => 'Tarikh Akhir',
            'assigned_by' => 'Ditugaskan Oleh',
            'assigned_to' => 'Ditugaskan Kepada',
            'actions' => 'Tindakan',
            'mark_complete' => 'Tandakan Selesai',
            'view_details' => 'Lihat Butiran',
            'add_task' => 'Tambah Tugasan',
            'edit_task' => 'Ubah Tugasan',
            'delete_task' => 'Padam Tugasan',
            'task_details' => 'Butiran Tugasan',
            'low' => 'Rendah',
            'medium' => 'Sederhana',
            'high' => 'Tinggi',
            'pending' => 'Belum Selesai',
            'completed' => 'Selesai',
            'overdue' => 'Lewat',
            'my_tasks' => 'Tugasan Saya',
'todays_tasks' => 'Tugasan Hari Ini',
'active_tasks' => 'Tugasan Aktif',
'tasks_history' => 'Sejarah Tugasan',
'task_list' => 'Senarai Tugasan',
'tasks' => 'tugasan',
'all_clear' => 'Semua Selesai',
'you_have_no' => 'Anda tiada',
'no_active_tasks' => 'Anda tiada tugasan aktif',
'no_today_tasks' => 'Anda tiada tugasan untuk hari ini',
'no_tasks_found' => 'Tiada tugasan dijumpai',
'auto' => 'AUTO',
'type' => 'Jenis',
'area' => 'Kawasan',
'bin' => 'Tong',
'full' => 'penuh',
'due' => 'Tarikh Akhir',
'overdue' => 'Lewat',
'at' => 'pada',
'view_on_map' => 'Lihat di Peta',
'complete_task' => 'Selesaikan Tugasan',
'add_completion_notes' => 'Tambah sebarang nota tentang tugasan ini (pilihan)',
'any_issues_placeholder' => 'Sebarang isu atau nota tentang penyiapan?',

// ============ TINDAKAN TUGASAN ============
'task_created_success' => 'Tugasan berjaya dicipta!',
'task_not_found' => 'Tugasan tidak dijumpai',
'cannot_edit_completed_cancelled' => 'Tidak boleh mengedit tugasan yang telah selesai atau dibatalkan',
'task_updated_success' => 'Tugasan berjaya dikemaskini!',
'auto_generated_collection_report_admin' => 'Laporan kutipan dijana automatik (pentadbir selesaikan)',
'cannot_cancel_completed' => 'Tidak boleh membatalkan tugasan yang telah selesai',
'task_cancelled_success' => 'Tugasan berjaya dibatalkan',
'only_pending_can_start' => 'Hanya tugasan yang belum selesai boleh dimulakan',
'task_started_success' => 'Tugasan berjaya dimulakan',
'task_not_found_not_assigned' => 'Tugasan tidak dijumpai atau tidak ditugaskan kepada anda',
'task_already_started' => 'Tugasan ini telah pun dimulakan',
'task_started_good_luck' => 'Tugasan dimulakan! Semoga berjaya! 💪',
'task_already_completed' => 'Tugasan ini sudah selesai',
'cannot_complete_cancelled' => 'Tidak boleh menyelesaikan tugasan yang dibatalkan',
'auto_generated_collection_report' => 'Laporan kutipan dijana automatik',
'task_completed_great_job' => 'Tugasan berjaya diselesaikan! Syabas! 🎉',
'task_deleted_success' => 'Tugasan berjaya dipadam',
'invalid_action_insufficient_permissions' => 'Tindakan tidak sah atau kebenaran tidak mencukupi',

// ============ PAPAN PEMUKA KEHADIRAN ============
'mark_your_attendance' => 'Tandakan Kehadiran Anda',
'go_to_check_in_out' => 'Pergi ke Daftar Masuk/Keluar',
'current_time' => 'Masa Semasa',
'present_days' => 'Kehadiran Awal',
'absent_days' => 'Hari Tidak Hadir',
'total_hours' => 'Jumlah Jam',
'attendance_records' => 'Rekod Kehadiran',
'no_records_found' => 'Tiada Rekod Dijumpai',
'no_attendance_records_month' => 'Tiada rekod kehadiran untuk bulan ini',
'check_in' => 'Daftar Masuk',
'check_out' => 'Daftar Keluar',
'hours' => 'Jam',
'todays_status' => 'Status Hari Ini',
'not_checked_in' => 'Belum Daftar Masuk',
'havent_checked_in_today' => 'Anda belum daftar masuk hari ini lagi.',
            
            // ============ HALAMAN DAFTAR MASUK/KELUAR ============
'check_in_out' => 'Daftar Masuk/Keluar',
'welcome' => 'Selamat Datang',
'please_select_employee' => "Sila pilih pekerja daripada menu 'Daftar Masuk/Keluar' dalam halaman Kehadiran",
'employee_not_found' => 'Pekerja tidak dijumpai',
'detecting_location' => 'Mengesan lokasi anda...',
'location_detected' => 'Lokasi berjaya dikesan',
'location_error' => 'Tidak dapat mengesan lokasi. Sila aktifkan GPS.',
'geolocation_not_supported' => 'Pelayar anda tidak menyokong geolokasi',
'location_not_detected_alert' => 'Lokasi tidak dikesan!',
'enable_gps_refresh' => 'Sila aktifkan GPS dan muat semula halaman.',
'todays_attendance_record' => 'Rekod Kehadiran Hari Ini',
'check_in_time' => 'Masa Daftar Masuk',
'check_out_time' => 'Masa Daftar Keluar',
'hours' => 'jam',
'check_in_now' => 'Daftar Masuk Sekarang',
'check_out_now' => 'Daftar Keluar',
'or' => 'Atau',
'back_to' => 'Kembali ke',
'my_attendance' => 'Kehadiran Saya',

// Mesej Status
'status_on_time' => 'Tepat Masa',
'status_late_arrival' => 'Kelewatan Ketibaan',
'status_very_late' => 'Sangat Lewat',

// Sebab Lewat
'reason_late_arrival' => 'Sebab Kelewatan Ketibaan',
'required' => 'Diperlukan',
'optional' => 'Pilihan',
'explain_late_reason' => 'Sila jelaskan mengapa anda daftar masuk lewat...',
'checkin_after_noon_warning' => 'Daftar masuk selepas 12 tengah hari memerlukan kelulusan pengurus. Sila berikan alasan yang sah.',
'late_reason_help' => 'Ini akan membantu pengurus anda memahami situasi.',

// ============ HALAMAN PRESTASI ============
'my_performance_report' => 'Laporan Prestasi Saya',
'back_to_dashboard' => 'Kembali ke Papan Pemuka',
'performance_report_for' => 'Laporan prestasi anda untuk',
'select_time_period' => 'Pilih Tempoh Masa',
'current_month' => 'Bulan Semasa',
'current_month_display' => date('F Y'),
'overall_performance_score' => 'Skor Prestasi Keseluruhan',
'task_completion_rate' => 'Kadar Penyiapan Tugasan',
'on_time_completion_rate' => 'Kadar Penyiapan Tepat Masa',
'attendance_rate' => 'Kadar Kehadiran',
'efficiency_score' => 'Skor Kecekapan',
'weight_30_percent' => 'Berat: 30% daripada skor keseluruhan',
'weight_25_percent' => 'Berat: 25% daripada skor keseluruhan',
'weight_15_percent' => 'Berat: 15% daripada skor keseluruhan',
'tasks_assigned' => 'Tugasan Ditugaskan',
'tasks_completed' => 'Tugasan Selesai',
'bins_collected' => 'Tong Dikutip',
'weight_collected' => 'Berat Dikutip',
'attendance_days' => 'Hari Kehadiran',
'avg_response_time' => 'Masa Respons Purata',
'on_time_tasks' => 'Tugasan Tepat Masa',
'performance_trend_6_months' => 'Trend Prestasi (6 Bulan Terakhir)',
'overall_score' => 'Skor Keseluruhan',
'completion_rate_chart' => 'Kadar Penyiapan',
'on_time_rate_chart' => 'Kadar Tepat Masa',
'attendance_rate_chart' => 'Kadar Kehadiran',
'last_7_days' => '7 Hari Lepas',
'last_30_days' => '30 Hari Lepas',
'all_time' => 'Sepanjang Masa',

// Gred Prestasi
'grade_excellent' => 'Cemerlang',
'grade_good' => 'Baik',
'grade_average' => 'Sederhana',
'grade_needs_improvement' => 'Perlu Penambahbaikan',
'grade_poor' => 'Lemah',

            // ============ CUTI ============
            'apply_leave' => 'Mohon Cuti',
            'leave_requests' => 'Permohonan Cuti',
            'leave_type' => 'Jenis Cuti',
            'start_date' => 'Tarikh Mula',
            'end_date' => 'Tarikh Akhir',
            'total_days' => 'Jumlah Hari',
            'reason' => 'Sebab',
            'emergency_contact' => 'Kenalan Kecemasan',
            'emergency_phone' => 'Telefon Kecemasan',
            'annual_leave' => 'Cuti Tahunan',
            'sick_leave' => 'Cuti Sakit',
            'emergency_leave' => 'Cuti Kecemasan',
            'unpaid_leave' => 'Cuti Tanpa Gaji',
            'maternity_leave' => 'Cuti Bersalin',
            'paternity_leave' => 'Cuti Paterniti',
            'approved' => 'Diluluskan',
            'rejected' => 'Ditolak',
            'cancelled' => 'Dibatalkan',
            'used_days' => 'Hari Digunakan',
            'remaining_days' => 'Hari Berbaki',
            'approve' => 'Luluskan',
            'reject' => 'Tolak',
            'submit_leave_for_approval' => 'Hantar permohonan cuti untuk kelulusan',
            'leave_request_form' => 'Borang Permohonan Cuti',
            'select_leave_type' => 'Pilih jenis cuti',
            'leave_reason_placeholder' => 'Sila berikan butiran untuk permohonan cuti anda...',
            'contact_person_during_leave' => 'Orang untuk dihubungi semasa cuti',
            'request_leave' => 'Mohon Cuti',
            'all' => 'Semua',
            'no_leave_requests_found' => 'Tiada permohonan cuti dijumpai',
            'havent_requested_leave' => 'Anda belum memohon sebarang cuti lagi',
            'request_leave_now' => 'Mohon Cuti Sekarang',
            'day' => 'hari',
            'applied' => 'Dimohon',
            'reviewed' => 'Disemak',
            'cancel_leave_confirm' => 'Batalkan permohonan cuti ini?',
            'cancel_request' => 'Batalkan Permintaan',
            'my_leave' => 'Percutian Saya',
            'only_employees_can_request_leave' => 'Hanya pekerja boleh memohon cuti',
'end_date_after_start_date' => 'Tarikh akhir mestilah selepas tarikh mula',
'invalid_leave_type' => 'Jenis cuti tidak sah',
'insufficient_leave_balance' => 'Baki cuti tidak mencukupi',
'you_have' => 'Anda mempunyai',
'days_remaining' => 'hari berbaki',
'overlapping_leave_request' => 'Anda sudah mempunyai permohonan cuti untuk tarikh yang bertindih',
'leave_request_submitted' => 'Permohonan cuti berjaya dihantar! Menunggu kelulusan.',
'invalid_leave_request_id' => 'ID permohonan cuti tidak sah',
'leave_request_not_found' => 'Permohonan cuti tidak dijumpai',
'cancel_own_leave_only' => 'Anda hanya boleh membatalkan permohonan cuti anda sendiri',
'only_pending_can_cancel' => 'Hanya permohonan cuti yang belum selesai boleh dibatalkan',
'leave_request_cancelled' => 'Permohonan cuti berjaya dibatalkan',
'only_admins_can_approve' => 'Hanya pentadbir boleh meluluskan permohonan cuti',
'already_processed' => 'Permohonan cuti ini telah diproses',
'leave_request_approved' => 'Permohonan cuti berjaya diluluskan',
'only_admins_can_reject' => 'Hanya pentadbir boleh menolak permohonan cuti',
'provide_rejection_reason' => 'Sila berikan sebab penolakan',
'leave_request_rejected' => 'Permohonan cuti ditolak',

            // ============ INVENTORI ============
            'inventory_management' => 'Pengurusan Inventori',
            'item_name' => 'Nama Barang',
            'total_items' => 'Jumlah Item',
            'search_items' => 'Cari item',
            'all_categories' => 'Semua Kategori',
            'min_quantity' => 'Kuantiti Min.',
            'category' => 'Kategori',
            'quantity' => 'Kuantiti',
            'current_quantity' => 'Kuantiti Semasa',
            'minimum_quantity' => 'Kuantiti Minimum',
            'unit' => 'Unit',
            'location' => 'Lokasi',
            'storage_location' => 'Lokasi Penyimpanan',
            'take' => 'Ambil',
            'request_restock' => 'Mohon Tambah Stok',
            'available' => 'Tersedia',
            'low_stock' => 'Stok Rendah',
            'out_of_stock' => 'Kehabisan Stok',
            'in_stock' => 'Ada Stok',
            'my_recent_transactions' => 'Transaksi Terkini Saya',
            'view_my_requests' => 'Lihat Permintaan Saya',
            'quantity_requested' => 'Kuantiti Dimohon',
            'urgency' => 'Kecemasan',
            'safety_gear' => 'Alat Keselamatan',
            'invalid_action' => 'Tindakan tidak sah',
'invalid_item_or_quantity' => 'Item atau kuantiti tidak sah',
'insufficient_stock' => 'Stok tidak mencukupi',
'only' => 'Hanya',
'of' => 'daripada',
'self_service_take' => 'Pengambilan layan diri',
'successfully_taken' => 'Berjaya diambil',
'remaining' => 'Baki',
'failed_to_record_transaction' => 'Gagal merekod transaksi',
'no_items_found' => 'Tiada Item Dijumpai',

// ============ TINDAKAN PERMINTAAN BEKALAN ============
'select_item_valid_quantity' => 'Sila pilih item dan masukkan kuantiti yang sah',
'invalid_urgency_level' => 'Tahap kecemasan tidak sah',
'restock_request_submitted' => 'Permintaan penambahan stok berjaya dihantar',
'your_request_for' => 'Permintaan anda untuk',
'awaiting_admin_approval' => 'sedang menunggu kelulusan pentadbir',
'quantity_to_restock' => 'Quantiti Untuk Restok',
'enter_quantity_restock' => '',
'why_need_this' => '',
'currently_available' => 'Tersedia pada masa ini',

            // ============ HALAMAN PERMINTAAN BEKALAN ============
            'inventory' => 'Inventori',
            'supply_requests' => 'Permintaan Bekalan',
'back_to_inventory' => 'Kembali ke Inventori',
'new_request' => 'Permintaan Baru',
'my_requests' => 'Permintaan Saya',
'reason_optional_recommended' => 'Sebab',
'submit_request' => 'Hantar Permintaan',
'submit_supply_request' => 'Hantar Permintaan Bekalan',
'select_item' => 'Pilih Item',
'choose_item' => 'Pilih item',
'available_stock' => 'Stok Tersedia',
'quantity_requested' => 'Kuantiti Dimohon',
'enter_quantity' => 'Masukkan kuantiti',
'urgency_low_desc' => 'Rendah',
'urgency_medium_desc' => 'Sederhana',
'urgency_high_desc' => 'Tinggi',
'reason_placeholder' => 'Mengapa anda perlukan item ini? Memberikan butiran membantu pentadbir memproses permintaan anda dengan lebih cepat.',
'reason_hint' => 'Contoh: "Perlukan beg sampah tambahan untuk acara pembersihan komuniti" atau "Penyapu semasa rosak"',
'total_requests' => 'Jumlah Permintaan',
'fulfilled' => 'Dipenuhi',
'all_requests' => 'Semua Permintaan',
'no_supply_requests_yet' => 'Tiada Permintaan Bekalan Lagi',
'havent_submitted_requests' => 'Anda belum menghantar sebarang permintaan bekalan',
'create_first_request' => 'Cipta Permintaan Pertama',
'priority' => 'Keutamaan',
'current_stock' => 'Stok Semasa',
'requested_date' => 'Tarikh Dimohon',
'processed_date' => 'Tarikh Diproses',
'your_reason' => 'Sebab Anda',
'admin_response' => 'Respons Pentadbir',
'reviewed_by' => 'Disemak oleh',
'awaiting_admin_review' => 'Menunggu semakan pentadbir...',
'item_restocked' => 'Item Ditambah Stok',
'awaiting_fulfillment' => 'Menunggu Pemenuhan',
'request_rejected' => 'Permintaan Ditolak',
            
            // ============ PENYELENGGARAAN ============
            'report_issue' => 'Laporkan Masalah',
            'my_reports' => 'Laporan Saya',
            'issue_title' => 'Tajuk Masalah',
            'issue_description' => 'Keterangan Masalah',
            'issue_category' => 'Kategori Masalah',
            'description' => 'Keterangan',
            'photo' => 'Gambar',
            'photo_evidence' => 'Bukti Gambar',
            'reported_by' => 'Dilaporkan Oleh',
            'reported_at' => 'Dilaporkan Pada',
            'resolved' => 'Diselesaikan',
            'resolved_at' => 'Diselesaikan Pada',
            'admin_notes' => 'Nota Pentadbir',
            'bin_issue' => 'Masalah Tong',
            'equipment_issue' => 'Masalah Peralatan',
            'facility_issue' => 'Masalah Kemudahan',
            'safety_hazard' => 'Bahaya Keselamatan',
            'other' => 'Lain-lain',
            'my_issue_reports' => 'Laporan Isu Saya',
'new_report' => 'Laporan Baru',
'total_reports' => 'Jumlah Laporan',
'in_progress' => 'Dalam Proses',
'all_status' => 'Semua Status',
'no_reports_yet' => 'Tiada Laporan Lagi',
'havent_submitted_reports' => 'Anda belum menghantar sebarang laporan penyelenggaraan',
'create_first_report' => 'Cipta Laporan Pertama',
'resolved_date' => 'Tarikh Diselesaikan',
'issue_photo' => 'Gambar isu',
'cancel_report_confirm' => 'Batalkan laporan ini? Tindakan ini tidak boleh dibuat asal.',
'cancel_report' => 'Batalkan Laporan',
'issue_resolved' => 'Isu Diselesaikan',
'being_worked_on' => 'Sedang Dikerjakan',

// ============ HALAMAN LAPORAN ISU ============
'submit_maintenance_report' => 'Hantar Laporan Penyelenggaraan',
'issue_title' => 'Tajuk Isu',
'issue_title_placeholder' => 'contoh: Penutup tong rosak di Kawasan A1',
'select_category' => 'Pilih kategori',
'issue_description' => 'Keterangan Isu',
'issue_description_placeholder' => 'Terangkan isu secara terperinci...',
'photo_evidence_optional' => 'Bukti Gambar',
'max_5mb_jpg_png' => 'Maks 5MB, JPG/PNG sahaja',
'photo_preview' => 'Pratonton gambar',
'location_placeholder' => 'contoh: Kawasan A1, Bangunan 3, Tingkat 2',
'submit_report' => 'Hantar Laporan',
'view_my_reports' => 'Lihat Laporan Saya',

// ============ TINDAKAN LAPORAN ============
'invalid_issue_category' => 'Kategori isu tidak sah',
'invalid_priority_level' => 'Tahap keutamaan tidak sah',
'report_submitted_success' => 'Laporan penyelenggaraan berjaya dihantar! Pentadbir akan menyemak laporan anda tidak lama lagi.',
'failed_upload_photo' => 'Gagal memuat naik gambar. Sila cuba lagi.',
'invalid_report_id' => 'ID laporan tidak sah',
'report_not_found_no_permission' => 'Laporan tidak dijumpai atau anda tidak mempunyai kebenaran untuk membatalkannya',
'only_pending_reports_cancel' => 'Hanya laporan yang belum selesai boleh dibatalkan. Laporan ini sudah sedang diproses.',
'report_cancelled_success' => 'Laporan berjaya dibatalkan.',

// Keterangan Keutamaan
'priority_low_desc' => 'Keutamaan rendah - akan ditangani apabila mungkin',
'priority_medium_desc' => 'Keutamaan biasa - akan ditangani tidak lama lagi',
'priority_high_desc' => 'Keutamaan tinggi - perhatian segera diperlukan!',

// Mesej Pengesahan
'file_size_error' => 'Saiz fail mesti kurang daripada 5MB!',
'file_type_error' => 'Hanya imej JPG dan PNG dibenarkan!',
'fill_all_required_fields' => 'Sila isi semua medan yang diperlukan!',
'title_too_short' => 'Tajuk isu mestilah sekurang-kurangnya 5 aksara!',
'description_too_short' => 'Sila berikan keterangan yang lebih terperinci (sekurang-kurangnya 10 aksara)!',
'confirm_submit_report' => 'Hantar laporan penyelenggaraan ini?',

            // ============ PROFIL ============
            'my_profile' => 'Profil Saya',
            'personal_information' => 'Maklumat Peribadi',
            'account_settings' => 'Tetapan Akaun',
            'language_settings' => 'Tetapan Bahasa',
            'full_name' => 'Nama Penuh',
            'email' => 'Emel',
            'phone' => 'Nombor Telefon',
            'address' => 'Alamat',
            'date_of_birth' => 'Tarikh Lahir',
            'hire_date' => 'Tarikh Mula Kerja',
            'position' => 'Jawatan',
            'department' => 'Jabatan',
            'change_password' => 'Tukar Kata Laluan',
            'current_password' => 'Kata Laluan Semasa',
            'new_password' => 'Kata Laluan Baru',
            'confirm_password' => 'Sahkan Kata Laluan',
            'update_profile' => 'Kemaskini Profil',
            'choose_language' => 'Pilih Bahasa',
            'select_language' => 'Pilih bahasa pilihan anda',
            'english' => 'English',
            'malay' => 'Bahasa Malaysia',
            
            // ============ BUTANG BIASA ============
            'submit' => 'Hantar',
            'cancel' => 'Batal',
            'save' => 'Simpan',
            'delete' => 'Padam',
            'edit' => 'Ubah',
            'back' => 'Kembali',
            'close' => 'Tutup',
            'confirm' => 'Sahkan',
            'add' => 'Tambah',
            'update' => 'Kemaskini',
            'create' => 'Cipta',
            'search' => 'Cari',
            'filter' => 'Tapis',
            'clear' => 'Kosongkan',
            'export' => 'Eksport',
            'import' => 'Import',
            'download' => 'Muat Turun',
            'upload' => 'Muat Naik',
            'print' => 'Cetak',
            'refresh' => 'Muat Semula',
            
            // ============ MESEJ ============
            'loading' => 'Memuatkan...',
            'no_data' => 'Tiada data tersedia',
            'success' => 'Berjaya',
            'error' => 'Ralat',
            'warning' => 'Amaran',
            'info' => 'Maklumat',
            'confirm_delete' => 'Adakah anda pasti ingin memadam ini?',
            'confirm_action' => 'Adakah anda pasti ingin meneruskan?',
            'saved_successfully' => 'Berjaya disimpan',
            'updated_successfully' => 'Berjaya dikemaskini',
            'deleted_successfully' => 'Berjaya dipadam',
            'operation_failed' => 'Operasi gagal',
            'please_fill_required_fields' => 'Sila isi semua ruangan yang diperlukan',
            'invalid_input' => 'Input tidak sah',
            'unauthorized_access' => 'Akses tidak dibenarkan',
            'language_updated' => 'Bahasa berjaya dikemaskini',
            
            // ============ MASA & TARIKH ============
            'today' => 'Hari Ini',
            'yesterday' => 'Semalam',
            'this_week' => 'Minggu Ini',
            'this_month' => 'Bulan Ini',
            'last_updated' => 'Kemaskini Terakhir',
            'created_at' => 'Dicipta Pada',
            'updated_at' => 'Dikemaskini Pada',
            'morning' => 'Pagi',
            'afternoon' => 'Tengahari',
            'evening' => 'Petang',
            
            // ============ STATISTIK ============
            'total' => 'Jumlah',
            'statistics' => 'Statistik',
            'overview' => 'Gambaran Keseluruhan',
            'summary' => 'Ringkasan',
            'details' => 'Butiran',
            'reports' => 'Laporan',
            'analytics' => 'Analitik',

            // Halaman Profil
    'my_profile' => 'Profil Saya',
    'edit_profile' => 'Ubah Maklumat Profil',
    'waste_collection_employee' => 'Pekerja Pengutipan Sisa',
    'change_photo' => 'Tukar Gambar',
    'not_set' => 'Tidak ditetapkan',
    'not_assigned' => 'Tidak ditugaskan',
    'joined' => 'Menyertai',
    'last_login' => 'Log Masuk Terakhir',
    'cannot_be_changed' => 'tidak boleh diubah',
    'area' => 'Kawasan',
    'note' => 'Nota',
    'admin_only_fields' => 'Nama pengguna, kawasan yang ditugaskan, dan status akaun hanya boleh diubah oleh pentadbir.',
    'enter_current_password' => 'Masukkan kata laluan semasa anda',
    'enter_new_password' => 'Masukkan kata laluan baru',
    'reenter_password' => 'Masukkan semula kata laluan baru',
    'minimum_6_characters' => 'minimum 6 aksara',
    'password_requirements' => 'Keperluan Kata Laluan',
    'password_requirement_text' => 'Sekurang-kurangnya 6 aksara. Gunakan kata laluan yang kuat untuk melindungi akaun anda.',
    'invalid_file_type' => 'Jenis fail tidak sah. Hanya JPG, JPEG, PNG, dan GIF dibenarkan.',
    'file_too_large' => 'Saiz fail mesti kurang daripada 5MB.',
    'profile_picture_updated' => 'Gambar profil berjaya dikemaskini!',
    'upload_failed' => 'Gagal memuat naik gambar profil.',
    'please_select_file' => 'Sila pilih fail imej yang sah.',
    'email_already_used' => 'Emel telah digunakan oleh akaun lain!',
    'profile_updated' => 'Profil berjaya dikemaskini!',
    'all_fields_required' => 'Semua medan kata laluan diperlukan!',
    'passwords_not_match' => 'Kata laluan baru tidak sepadan!',
    'password_min_length' => 'Kata laluan baru mestilah sekurang-kurangnya 6 aksara!',
    'current_password_incorrect' => 'Kata laluan semasa tidak betul!',
    'password_changed' => 'Kata laluan berjaya ditukar!',
        ]
    ];
    
    return $languages[$lang] ?? $languages['en'];
}

function t($key, $lang = null) {
    if ($lang === null) {
        $lang = $_SESSION['language'] ?? 'en';
    }
    
    $strings = getLanguageStrings($lang);
    return $strings[$key] ?? $key;
}
?>